version: "3.9"
services:
  redis_single:
    image: elasticsearch:7.10.1
    container_name: "es1"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
networks:
  elastic:
    driver: bridge


